#!/usr/bin/env bash
#
# Where Keel is and how to sign in.
#
#   scripts/ops/keel-url.sh
#
# The credentials are generated by the PreSync hook, not chosen by anyone, so
# this reads them back rather than reminding you of something you picked. That
# is the point: a password nobody types is a password nobody can leave empty,
# which is what happened twice on 2026-09-07.

set -euo pipefail

NAMESPACE="${KEEL_NAMESPACE:-insighta-prod}"
SECRET="${KEEL_AUTH_SECRET:-keel-basic-auth}"
URL="${KEEL_URL:-https://insighta.one/keel/}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

OUT=$(bash "$HERE/ssh.sh" k3s \
  "kubectl get secret $SECRET -n $NAMESPACE -o jsonpath='{.data.username}|{.data.password}'" \
  2>/dev/null)

USER_B64="${OUT%%|*}"
PASS_B64="${OUT##*|}"

if [ -z "$PASS_B64" ]; then
  echo "no generated credentials in $SECRET yet." >&2
  echo "the PreSync hook writes them; check it ran:" >&2
  echo "  scripts/ops/ssh.sh k3s \"kubectl logs -n $NAMESPACE job/insighta-keel-provision\"" >&2
  exit 1
fi

printf '\n  %s\n\n' "$URL"
printf '  user      %s\n' "$(printf '%s' "$USER_B64" | base64 -d)"
printf '  password  %s\n\n' "$(printf '%s' "$PASS_B64" | base64 -d)"
